"""empty message

Revision ID: 190664cb431a
Revises: 
Create Date: 2020-08-22 07:39:09.496949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190664cb431a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'actor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'movie',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'catogry',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'movie',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'movie',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'catogry',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'movie',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'actor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
